# Generated by Django 6.0.4 on 2026-04-13 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('odoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSalesOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_id', models.IntegerField()),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('odoo_order_id', models.IntegerField(blank=True, null=True)),
                ('odoo_order_name', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sales_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_sales_orders', to='accounts.salesagent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_sales_orders', to='core.tenant')),
            ],
        ),
    ]
